version: 2.1
orbs:
  pack: buildpacks/pack@0.2.0
executors:
  # pack-exec:
  #   docker:
  #     - image: circleci/ruby:2.5.1-node-browsers
  #       auth:
  #         username: dfreilich
  #         password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
workflows:
  main:
    jobs:
      - pack/build:
          # image-name: dfreilich/hello-buildpacks:circle-ci
          image-name: hello-buildpacks
          builder: 'paketobuildpacks/builder:tiny'
          working_directory: 'app/'
      - test:
          requires:
            - pack/build
jobs:
  test:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            docker load -i /tmp/workspace/images/image.tgz
            docker run -d -p 8080:8080 hello-buildpacks
            curl localhost:8080/
